### ISSUE TITLE
`docker_push` fails for example acr

### ISSUE THREAD

**Issue by Menghua1** [Azure/terraform-azurerm-avm-res-app-containerapp#38] opened 2024-07-30 02:36 UTC
**Describe the issue:**
When test the example [acr](https://registry.terraform.io/modules/Azure/avm-res-app-containerapp/azurerm/latest/examples/acr) of module `avm-res-app-containerapp`, it returns the error below.
![image](https://github.com/user-attachments/assets/1bd47bef-e413-41d1-a15f-195d7c69dcad)
However, if the VPN is disconnected before the `docker_push`, it eventually runs successfully.
![image](https://github.com/user-attachments/assets/e17240dc-0518-4ecd-8a51-bfe68eb88a1f)

**Module Version:** 0.1.0

**Examples:** [acr](https://registry.terraform.io/modules/Azure/avm-res-app-containerapp/azurerm/latest/examples/acr)

**Repro Steps:**

1. Execute commands: `azd login`, `az login`.
2. Clone terraform template code. E.g:`todo-python-mongo-terraform`
3. Copy and paste the example [acr](https://registry.terraform.io/modules/Azure/avm-res-app-containerapp/azurerm/latest/examples/acr) into main.tf.
4. Annotate the contents of the `infra/output.tf` file.
5. Run `azd provision`.

**Expected behavior:**
The examples [acr](https://registry.terraform.io/modules/Azure/avm-res-app-containerapp/azurerm/latest/examples/acr) can be tested successfully.

@lonegunmanb and @jongio for notification.

**Comment by lonegunmanb** [comment] 2024-09-20 06:14
Thanks @Menghua1 for reporting this issue to us. The `acr` example used `docker push` to push nginx image to newly created Acr so I think this example is fine. Sometimes VPN, especially MS VPN would block you from accessing some Azure service, I would recommend you trying this `acr` example in GitHub Codespace environment to double check whether it's a network issue or not.

**Comment by Menghua1** [comment] 2024-09-23 08:55
> Thanks @Menghua1 for reporting this issue to us. The `acr` example used `docker push` to push nginx image to newly created Acr so I think this example is fine. Sometimes VPN, especially MS VPN would block you from accessing some Azure service, I would recommend you trying this `acr` example in GitHub Codespace environment to double check whether it's a network issue or not.

@lonegunmanb I tested this [acr](https://registry.terraform.io/modules/Azure/avm-res-app-containerapp/azurerm/latest/examples/acr) example in the GitHub Codespace environment and did not encounter this issue.

**Comment by lonegunmanb** [comment] 2024-11-22 08:31
@Menghua1 Thanks for confirming that. I'm closing this issue since we cannot reproduce it, but please feel free to reopen it if you have different thought.

**Closed by lonegunmanb** 2024-11-22 08:31 UTC
Labels: Needs: Immediate Attention :bangbang:, Needs: Triage :mag:, Status: Response Overdue :triangular_flag_on_post:
